version: 2.1
jobs:
  build:
    working_directory: ~/python-sample
    docker:
      - image: "cimg/python:3.10.1"
    steps:
      - checkout
      - run: python main.py    
  test:
    working_directory: ~/python-sample
    docker:
      - image: "cimg/python:3.10.1"
    steps:
      - checkout
      - run: python main-test.py

workflows:
  run_and_test:
    jobs:
    - build
    - test:
        requires:
          - build